### ISSUE TITLE
Tests on Windows

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/Optimize.jl#41]
The Windows tests keep failing because of AmplNLReader. We should eliminate that package from the tests and e.g., hard-code one problem and its derivatives instead.

**Comment by abelsiqueira** [comment]
Drop only for windows?

**Comment by dpo** [comment]
Drop everywhere I think. This package is useable without AMPL and the tests should be platform independent.

**Comment by abelsiqueira** [comment]
> tests should be platform independent

That would mean dropping CUTEst for Windows.

**Comment by dpo** [comment]
[The tests don't use CUTEst](https://github.com/JuliaSmoothOptimizers/Optimize.jl/blob/master/test/REQUIRE)?!?!

**Comment by dpo** [comment]
Ah, that's right. But it's not really **required**, is it?

**Comment by abelsiqueira** [comment]
We use it [here](https://github.com/JuliaSmoothOptimizers/Optimize.jl/blob/master/test/runtests.jl#L10) and [here](https://github.com/JuliaSmoothOptimizers/Optimize.jl/blob/master/test/runtests.jl#L38). But it's true, it's not really required, since it doesn't test anything new. We can drop it.

**Comment by dpo** [comment]
We use it but it isn't in `REQUIRE`. I believe we wanted to check that the solvers performed similarly whatever the provenance of the problem. It's useful I guess. We could keep it but there should be tests that don't need CUTEst or AmpNLReader.
